### ISSUE TITLE
Unable to connect to my local instance

### ISSUE THREAD

**Issue by alexxx0788** [obukhov/redis-inventory#70]
I have my local Redis instance with no password running port 6380, but I am getting ' connection refused' messsage.
What should I do?
![image](https://user-images.githubusercontent.com/915103/177018892-fea7a1da-e760-4808-b243-f489f938a61d.png)

**Comment by Rezab98** [comment]
You should user [host network](https://docs.docker.com/network/host/) in cocker

**Comment by perry0517** [comment]
you should use [host network](https://docs.docker.com/network/host/), and use host.docker.internal to connect your host
<img width="844" alt="image" src="https://github.com/obukhov/redis-inventory/assets/6801271/93caa5eb-5fe0-495f-b2ae-f7c6e9bf903d">

**Comment by obukhov** [comment]
I assume the issue is solved. Using host.docker.internal is needed if you use docker-packed app, you don't need it if you use the binary
